version: '3.4'

networks:
  project-documentation-network:
    driver: bridge

services:
  webapi:
    image: project-documentation-webapi
    build:
      context: ./server
      dockerfile: Web/WebApi/Dockerfile
    container_name: project-documentation-webapi
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_WEBAPI_URLS}
    ports:
      - 81:81
    networks:
      - project-documentation-network

  webui:
    image: project-documentation-webui
    build:
      context: ./webui
      dockerfile: ./Dockerfile
    container_name: project-documentation-webui
    restart: on-failure
    ports:
      - 3000:3000
    networks:
      - project-documentation-network
    depends_on:
      - webapi
    volumes:
      - ./webui:/app
      - node_modules:/app/node_modules

  nginx:
    image: project-documentation-nginx
    build:
      context: ./network
      dockerfile: ./Nginx/Dockerfile
    ports:
      - 80:80
    container_name: project-documentation-nginx
    networks:
      - project-documentation-network
    depends_on:
      - webapi
      - webui
    volumes:
      - ./network/Nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  node_modules:
    name: webui-node-modules