version: '3.4'

networks:
  project-documentation-network:
    driver: bridge

services:
  webapi:
    image: project-documentation-webapi
    build:
      context: ./server
      dockerfile: Web/WebApi/Dockerfile
    container_name: project-documentation-webapi
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_WEBAPI_URLS}
      - ConnectionStrings__DefaultConnection=${ASPNETCORE_WEB_CONNECTION_STRING}
    ports:
      - '81:81'
    networks:
      - project-documentation-network

  webui:
    image: project-documentation-webui
    build:
      context: ./webui
      dockerfile: ./Dockerfile
    container_name: project-documentation-webui
    restart: on-failure
    ports:
      - '3000:3000'
    networks:
      - project-documentation-network
    environment:
      - VITE_BASE_URL=${VITE_BASE_URL}
      - VITE_AZURE_CLIENT_ID=${VITE_AZURE_CLIENT_ID}
      - VITE_AZURE_AUTHORITY=${VITE_AZURE_AUTHORITY}
      - VITE_AZURE_REDIRECT_URI=${VITE_AZURE_REDIRECT_URI}
      - VITE_AZURE_GRAPH_SCOPES=${VITE_AZURE_GRAPH_SCOPES}
      - VITE_AZURE_API_SCOPES=${VITE_AZURE_API_SCOPES}
      - VITE_OPEN_AI_API_KEY=${VITE_OPEN_AI_API_KEY}
      - VITE_TINY_MCE_API_KEY=${VITE_TINY_MCE_API_KEY}
    depends_on:
      - webapi
    volumes:
      - ./webui:/app
      - webui-node_modules:/app/node_modules

  jiraoauth:
    image: project-documentation-jiraoauth
    build:
      context: ./jira-applications/jira-oauth
      dockerfile: ./Dockerfile
    container_name: project-documentation-jiraoauth
    restart: on-failure
    environment:
      - JIRA_OAUTH_CLIENT_ID=${JIRA_OAUTH_CLIENT_ID}
      - JIRA_OAUTH_CLIENT_SECRET=${JIRA_OAUTH_CLIENT_SECRET}
      - JIRA_OAUTH_CALLBACK_URL=${JIRA_OAUTH_CALLBACK_URL}
      - PORT=${JIRA_OAUTH_PORT}
      - NODE_ENV=${JIRA_OAUTH_NODE_ENV}
    ports:
      - '8000:8000'
    networks:
      - project-documentation-network
    volumes:
      - ./jira-applications/jira-oauth:/app
      - jira-oauth-node_modules:/app/node_modules

  nginx:
    image: project-documentation-nginx
    build:
      context: ./network
      dockerfile: ./Nginx/Dockerfile
    ports:
      - '80:80'
    container_name: project-documentation-nginx
    networks:
      - project-documentation-network
    depends_on:
      - webapi
      - webui
      - jiraoauth
    volumes:
      - ./network/Nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  webui-node_modules:
    name: webui-node-modules

  jira-oauth-node_modules:
    name: jira-oauth-node-modules
