version: '3.4'

networks:
  project-documentation-network:
    driver: bridge

services:
  webapi:
    image: project-documentation-webapi
    build:
      context: ./server
      dockerfile: Web/WebApi/Dockerfile
    container_name: project-documentation-webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_WEBAPI_URLS}
      - ASPNETCORE_AUTH0_DOMAIN=${ASPNETCORE_AUTH0_DOMAIN}
      - ASPNETCORE_AUTH0_CLIENT_ID=${ASPNETCORE_AUTH0_CLIENT_ID}
      - ASPNETCORE_AUTH0_AUDIENCE=${ASPNETCORE_AUTH0_AUDIENCE}
      - ConnectionStrings__DefaultConnection=${ASPNETCORE_WEB_CONNECTION_STRING}
    ports:
      - "81:81"
    networks:
      - project-documentation-network

  webui:
    image: project-documentation-webui
    build:
      context: ./webui
      dockerfile: ./Dockerfile
    container_name: project-documentation-webui
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - project-documentation-network
    environment:
      - VITE_BASE_URL=${VITE_BASE_URL}
      - VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
      - VITE_AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN}
      - VITE_OPEN_AI_API_KEY=${VITE_OPEN_AI_API_KEY}
      - VITE_TINY_MCE_API_KEY=${VITE_TINY_MCE_API_KEY}
    depends_on:
      - webapi
    volumes:
      - ./webui:/app
      - ./webui/node_modules:/app/node_modules

  nginx:
    image: project-documentation-nginx
    build:
      context: ./network
      dockerfile: ./Nginx/Dockerfile
    ports:
      - "80:80"
    container_name: project-documentation-nginx
    networks:
      - project-documentation-network
    depends_on:
      - webapi
      - webui
    volumes:
      - ./network/Nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  node_modules:
    name: webui-node-modules